# frozen_string_literal: true

# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['MAILJET_API_KEY']
  config.api_version = 'v3.1'
  config.secret_key = ENV['MAILJET_API_SECRET']
  config.default_from = ENV['MAILJET_API_DEFAULT_FROM']
end
